### ISSUE TITLE
Coordinates are still confusing

### ISSUE THREAD

**Issue by xerus2000** [CAU-Kiel-Tech-Inf/server#257]
![image](https://user-images.githubusercontent.com/13354331/73260267-de2dd900-41c9-11ea-801b-4b3c3f66c3c5.png)

The Bee is displayed on position (5, -4, 1) in the debug view, while it is on (-1, 5, -4). Is this just a problem of the debug output? Or the structure of the Board?

![image](https://user-images.githubusercontent.com/13354331/73260301-ed148b80-41c9-11ea-85ad-58c932d184ac.png)
![image](https://user-images.githubusercontent.com/13354331/73260789-f2bea100-41ca-11ea-9cff-a97ab999043f.png)

**Comment by SKoschnicke** [comment]
Hive development is finalized.
